[theme]
base = "dark"
primaryColor = "#67E2C4"
backgroundColor = "#0A1322"
secondaryBackgroundColor = "#14243A"
textColor = "#E7EFF9"

[server]
maxUploadSize = 100

[browser]
gatherUsageStats = false
